/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package combo.gui.consulta;

import javax.swing.JDialog;
import javax.swing.JButton;
import javax.swing.JLabel;
import combo.controller.CoConsulta;


public class GuiConsulta extends javax.swing.JDialog {

    /**
     * Creates new form GuiConsulta
     */
    public GuiConsulta(java.awt.Frame parent, boolean modal, String title) {
        super(parent, modal);
        initComponents();
        this.setTitle(title);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setModal(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        // Botões de navegação com melhor design
        btnPrimeira = new JButton("Primeira");
        btnPrimeira.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnPrimeira.setBackground(new java.awt.Color(230, 230, 250));
        btnPrimeira.setToolTipText("Ir para a primeira página");
        btnPrimeira.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8)));

        btnAnterior = new JButton("Anterior");
        btnAnterior.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnAnterior.setBackground(new java.awt.Color(230, 230, 250));
        btnAnterior.setToolTipText("Ir para a página anterior");
        btnAnterior.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8)));

        btnProxima = new JButton("Próxima");
        btnProxima.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnProxima.setBackground(new java.awt.Color(230, 230, 250));
        btnProxima.setToolTipText("Ir para a próxima página");
        btnProxima.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8)));

        btnUltima = new JButton("Última");
        btnUltima.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnUltima.setBackground(new java.awt.Color(230, 230, 250));
        btnUltima.setToolTipText("Ir para a última página");
        btnUltima.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8)));

        // Painel de status com fonte melhorada
        lblStatus = new JLabel("Página 1 de 1 (Total: 0 registros)");
        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setBackground(new java.awt.Color(230, 230, 250));
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable.setRowHeight(25);
        jTable.setShowGrid(true);
        jTable.setGridColor(new java.awt.Color(200, 200, 200));
        jTable.setSelectionBackground(new java.awt.Color(184, 207, 229));
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnPrimeira)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProxima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUltima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatus)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 208,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnPrimeira)
                                        .addComponent(btnAnterior)
                                        .addComponent(btnProxima)
                                        .addComponent(btnUltima)
                                        .addComponent(lblStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }// GEN-LAST:event_formWindowActivated

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        System.err.println(jTable.getSelectedRow());
    }// GEN-LAST:event_jTableMouseClicked
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    private JButton btnPrimeira, btnAnterior, btnProxima, btnUltima;
    private JLabel lblStatus;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JScrollPane getjScrollPane() {
        return jScrollPane;
    }

    public void setjScrollPane(javax.swing.JScrollPane jScrollPane) {
        this.jScrollPane = jScrollPane;
    }

    public javax.swing.JTable getjTable() {
        return jTable;
    }

    public void setjTable(javax.swing.JTable jTable) {
        this.jTable = jTable;
    }

    public void setStatus(String texto) {
        lblStatus.setText(texto);
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setForeground(new java.awt.Color(0, 51, 102));
    }

    public void setController(CoConsulta controller) {
        btnPrimeira.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                try {
                    controller.irParaPrimeiraPagina();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                try {
                    controller.paginaAnterior();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
        btnProxima.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                try {
                    controller.proximaPagina();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
        btnUltima.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                try {
                    controller.irParaUltimaPagina();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
}
